org: viniciusls
app: serverless-card-processor
service: serverless-card-processor

provider:
  name: openwhisk

functions:
  card:
    handler: app.process
    events:
      - http: GET process

plugins:
  - serverless-openwhisk
